// @ts-check

/**
 * Treemble Documentation Sidebar
 *
 * This version manually defines the structure and order of your docs.
 * You can group items, set custom labels, and include/exclude docs.
 *
 * To revert to autogenerated, just comment this out and uncomment the original.
 */

const sidebars = {
  tutorialSidebar: [
    'intro',  // maps to docs/intro.md
    {
      type: 'category',
      label: 'Using Treemble',
      collapsed: false,  // keeps this category open by default
      items: [
        'getting-started',
        'ui-overview',
        'placing-nodes',
        'scale-calibration',
        'showing-the-tree-and-fixing-problems',
        'adding-and-editing-tip-names',
        'showing-and-saving-a-newick-file',
        'options',
        'blank-canvas-and-drawing-tools',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Features',
      collapsed: false,
      items: [
        'circular-trees',
        'node-locations-csv-files',
        'diff-tip-names-in-a-csv-file'
      ],
    },
    {
      type: 'category',
      label: 'Support',
      collapsed: false,
      items: [
        'troubleshooting',
        'shortcuts',
        'use-cases',
      ],
    },
  ],
};

export default sidebars;
